### ISSUE TITLE
Add-on Submissions 22W52

### ISSUE THREAD

**Issue by DaveBowman2001** [levinli303/celestia.mobi#47]
Submit your add-ons in this issue, thanks for your contribution!
The new submission template has been changed as of 2022-Dec-23. Everything should be packaged in a .zip file. The zip file should be structured like this, those marked * are mandatory (whether it is making a new one or making change to the existing one):
```
title.txt *
description.txt *
authors.txt
release_date.txt *
last_update_date.txt
category.txt *
demo_object_name.txt *
localized_titles.json
localized_descriptions.json
addon.zip *
cover_image.jpg *
id_requirement.txt

rich_description (folder, optional, if provided, those marked * are mandatory)
- base.txt *
- notes.txt
- cover_image.jpg *
- cover_image.txt
- youtube_ids.txt
- detail_image_x.jpg
- detail_image_x.txt
- additional_leading.html
- additional_trailing.html
```
## What should be the Content of Each File Above?
BASE FILES
- **title.txt** = Title of the add-on
- **description.txt** = Plain description of the add-on, do not insert empty line between two paragraphs
- **authors.txt** = Authors, one author per line.
- **release_date.txt** = Release date in `yyyy/MM/dd HH:mm:ss` format, GMT time zone
- **last_update_date.txt** = Last update date in `yyyy/MM/dd HH:mm:ss` format, GMT time zone
- **category.txt** = Category ID, for example `https://celestia.mobi/resources/category?category=DEAF9C38-7E4B-7DFB-CA72-B496B1652550` has category ID `DEAF9C38-7E4B-7DFB-CA72-B496B1652550`
- **demo_object_name.txt** = Demo object name of the add-on
- **localized_titles.json** = Localized title in JSON format, used for non-English locale, for example `{ "zh_CN": "标题" }`
- **localized_descriptions.json** = Localized plain description in JSON format, used for non-English locale, for example` { "zh_CN": "介绍" }`
- **addon.zip** = Addon
- **cover_image.jpg** = Cover image
- **id_requirement.txt** = ID requirement for the add-on ID to start with or the add-on ID to modify if provided in full

FOR THE RICH DESCRIPTION:
- **rich_description** = Rich description folder
- **base.txt** = The first part of rich description text
- **notes.txt** = Notes, one note per line
- **cover_image.jpg** = Cover image
- **cover_image.txt** = Caption for cover image
- **youtube_ids.txt** = YouTube ID, one ID per line, for example `https://www.youtube.com/watch?v=g2ra7EdttTQ` has ID `g2ra7EdttTQ`
- **detail_image_x.jpg** = Other image, x will be replaced with number starting from 0
- **detail_image_x.txt** = Captions for other image x
- **additional_leading.html** = Raw HTML content inserted after cover image
- **additional_trailing.html** = Raw HTML content inserted at the end

Rich description will look like
```
base
NOTES:
- note 1
- note 2
cover image
cover image caption
additional leading HTML
youtube links
detail image 1
detail image caption 1
detail image 2
detail image caption 2
additional trailing HTML
```
## Additional Important Notes
- You can have links in `base.txt` and `notes.txt`, use `<a href="link">link display name</a>`.
- For add-on links, use `celaddon://item?item=ADDON_ID`, for articles use `celguide://guide?guide=GUIDE_ID` as link.
- Line breaks are ignored in `base.txt`, replace line breaks with `<br>`, replace `>` with `&gt;`, and `<` with `&lt;`

## For Updates to Existing Add-ons
For updates to existing add-ons, do not forget to attach the ID of the addon you want to update, and only provide details written above that needs to be updated

The id is part of the link to the add-on:
For example, this addon below has an id of A4577B17-4C60-0C1E-CAB5-92A604FF0EC3
https://celestia.mobi/resources/item?item=A4577B17-4C60-0C1E-CAB5-92A604FF0EC3

## For Removing Outdated Add-ons
The process of removing addons are the same as updating them, except that `authors.txt` and `category.txt` are no longer required

## **Check Before Uploading an Add-on**

Your add-on will be running on Android/iOS/macOS/Windows, to enable maximum compatibility, please ensure that:

1. File names referenced in **models**, **ssc**, **dsc** files, etc. are exactly the same as the actual file names (some file systems are case sensitive. For example if in your .ssc there is `Mesh "Progress.cmod"`, then the file name should be exactly `Progress.cmod` not `progress.cmod`).
2. Textures should have width/height of power of 2 (for example: 1024 * 512, a texture of 1000 * 500 will not work on many mobile devices).
3. If your add-on requires specific Celestia versions, please mention in the description. Please also ensure that your add-on should not crash running on other versions.
4. If you are updating an existing add-on, note that existing users will not see an update button, so it might be a good idea to include version history in the description.
5. Please try to use smaller files for image/thumbnail/other metadata. For example, use JPG if alpha value is not needed.
6. All images need to be in JPEG (you either choose to screenshot in JPEG in Celestia or convert using tools)
7. The add-on archive should not include system files or hidden files (macOS is notorious for adding hidden system files to archives, avoid using macOS's default archive utility) this issue is found in many add-ons @Anthony-B-Russo10 uploaded
8. The add-on archive must have a flat folder structure (It should try to have fewer level of folders, do not do things like A/A/A) this issue is found in many add-ons @SpaceExplorer2008 uploaded

## Alternate Submission Method
As of 2022-Dec-28, another submission method has been started. If you have an Apple ID, you can submit your addon through the following link below:
### [ADDON SUBMISSION LINK](https://celestia.mobi/update-addon)
IMPORTANT NOTE:
- Always remember that everytime you have a successful submission through that link, don't forget to copy the generated ID and post it here on this GitHub issue like the example below:
![image](https://user-images.githubusercontent.com/95486841/209898791-13f89691-af47-45cd-b966-8677a7dc851a.png)

**Comment by DaveBowman2001** [comment]
**Title**: Project Apollo
**ID Requirement**: A
**Proposed category**: Spacecraft: Crewed/Resupply Missions
**Demo Object**: Eagle LEM
**Author(s)**: DaveBowman2001, ElChristou, Endeavor35, Max Grüeter
**Last updated**: 2022-Dec-11
**Link to download**: 
**Image**:
![Untitled](https://user-images.githubusercontent.com/95486841/207524054-14e9002e-cd37-412a-82e9-1d1bdee5e720.jpg)

**Comment by DaveBowman2001** [comment]
**Title**: Apollo-Soyuz Test Project
**ID Requirement**: 45
**Description (Plain Text)**: The Apollo-Soyuz Test Project (ASTP) is the first crewed international space mission in history, carried out jointly by the United States and the Soviet Union in July 1975. It symbolized the end of the Space Race that started with the launch of Sputnik 1 in 1957 and reached its peak during Apollo 11 in 1969. ASTP marked the last flight of the Apollo Program, with the US portion sometimes being referred to (unofficially) as Apollo 18. The mission's legacy on peaceful cooperation in space is still felt today aboard the International Space Station since 1998

**Description**: The Apollo-Soyuz Test Project (ASTP) is the first crewed international space mission in history, carried out jointly by the United States and the Soviet Union in July 1975. It symbolized the end of the Space Race that started with the launch of Sputnik 1 in 1957 and reached its peak during Apollo 11 in 1969. ASTP marked the last flight of the Apollo Program, with the US portion sometimes being referred to (unofficially) as Apollo 18. The mission's legacy on peaceful cooperation in space is still felt today aboard the International Space Station since 1998

NOTES:
- Requires the Project Apollo addon installed in order to see the full ASTP mission in action. Without it, by default only the Soyuz missions are visible on this addon
- Also includes the three precursor test flights and one post-ASTP mission of the Soyuz 7K-TM spacecraft (see Table below)

![Untitled](https://user-images.githubusercontent.com/95486841/207517727-36670c82-74c6-4c44-9a49-eaf99ed81044.jpg)
_Apollo-Soyuz, also known as Soyuz-Apollo in the USSR, docked together on July 1975_

![Untitled](https://user-images.githubusercontent.com/95486841/207517842-090f380e-c4f4-4df8-961e-495f7d432fee.jpg)
_Apollo 18_

![Untitled](https://user-images.githubusercontent.com/95486841/207518176-4a98a1ed-5218-418f-95ba-9a1609bf044b.jpg)
_Soyuz 19_

```
<table class="astp-chart">
  <style>.satcom-chart th { text-align:center;position:static  } .astp-chart td { text-align:center }</style>
  <tbody>
    <tr>
      <th colspan="6">Apollo-Soyuz<br>(1974-1975)</th>
    </tr>
    <tr>
      <th colspan="2">Mission</th>
      <th>Start</th>
      <th>End</th>
    </tr>
    <tr>
      <td colspan="2" rowspan="2"><strong>Cosmos 638</strong></td>
      <td>1974-Apr-3</td><td>1974-Apr-13</td>
    </tr>
    <tr>
      <td colspan="2"><i>Unmanned test flight of the Soyuz 7K-TM</i></td>
    </tr>
    <tr>
      <td colspan="2" rowspan="2"><strong>Cosmos 672</strong></td>
      <td>1974-Aug-12</td><td>1974-Aug-18</td>
    </tr>
    <tr>
      <td colspan="2"><i>Unmanned test flight of the Soyuz 7K-TM</i></td>
    </tr>
    <tr>
      <td colspan="2" rowspan="2"><strong>Soyuz 16</strong></td>
      <td>1974-Dec-2</td><td colspan="2">1974-Dec-8</td>
    </tr>
    <tr>
      <td colspan="2"><i>Crewed test flight/dress rehearsal before ASTP</i></td>
    </tr>
    <tr>
      <td rowspan="3"><strong>Apollo-Soyuz Test Project (ASTP)</strong></td><td><strong>Soyuz 19</strong></td>
      <td rowspan="2">1975-Jul-15</td><td>1975-Jul-21</td>
    </tr>
    <tr>
      <td><strong>Apollo 18</strong><td>1975-Jul-24</td>
    </tr>
    <tr>
      <td colspan="3"><i>First international crewed spaceflight in history</i></td>
    </tr>
    <tr>
      <td colspan="2" rowspan="2"><strong>Soyuz 22</strong></td>
      <td>1976-Sept-15</td><td>1976-Sept-23</td>
    </tr>
    <tr>
      <td colspan="2"><i>Final non-space station crewed mission of the Soyuz spacecraft</i></td>
    </tr>
  </tbody>
</table>
```
_Timeline of the ASTP program and related spaceflights, 1974-1975_

![Untitled](https://user-images.githubusercontent.com/95486841/207520888-d73e4f65-e0d5-440d-95db-6842ca8ce93f.jpg)
_The two crews of Apollo-Soyuz: (Top) Tom Stafford and Alexei Leonov, (Below) Deke Slayton, Vance Brand and Valery Kubasov_

**Proposed category**: Spacecraft: Crewed/Resupply Missions
**Demo Object**: ASTP
**Author(s)**: DaveBowman2001, linuxman
**Release date**: 2006-Sept-14
**Last updated**: 2022-Dec-11
**Link to download**: [Apollo-Soyuz Test Project.zip](https://github.com/levinli303/celestia.mobi/files/10224763/Apollo-Soyuz.Test.Project.zip)
**Image**:
![Untitled](https://user-images.githubusercontent.com/95486841/207517727-36670c82-74c6-4c44-9a49-eaf99ed81044.jpg)

**Comment by DaveBowman2001** [comment]
Update to the "**Skylab**" addon. Removed all Apollo-related files in the addon as it is already provided by _Project Apollo (Part 4)_. Also an updated description, but its main gallery remains the same

**ID**: [79FFB1A2-4DB3-7783-F863-0CB807D52AFB](https://celestia.mobi/resources/item?item=79FFB1A2-4DB3-7783-F863-0CB807D52AFB)
**Description (Plain Text)**: Skylab was NASA's first space station, where it was launched and operated by three separate three-Apollo crews from May 1973 to February 1974. Major operations included an orbital workshop, a solar observatory, Earth observation, and hundreds of experiments. Unable to be re-boosted by the Space Shuttle, which was not ready until 1981, Skylab's orbit eventually decayed, and it disintegrated in the atmosphere on July 11, 1979, scattering debris across the Indian Ocean and Western Australia.

NOTE: Requires the Project Apollo addon installed first in order to see the three visiting missions from 1973-1974

**Description**: Skylab was NASA's first space station, where it was launched and operated by three separate three-Apollo crews from May 1973 to February 1974. Major operations included an orbital workshop, a solar observatory, Earth observation, and hundreds of experiments. Unable to be re-boosted by the Space Shuttle, which was not ready until 1981, Skylab's orbit eventually decayed, and it disintegrated in the atmosphere on July 11, 1979, scattering debris across the Indian Ocean and Western Australia.

NOTES:
- Requires the Project Apollo addon installed to view the three missions and various EVAs from 1973-1974
- Since Skylab no longer orbits the Earth in real life, you can only view it on Celestia from May 1973 to July 1979
- Replaces and enhances the stock version of Skylab included on Celestia by default

**Author(s)**: DaveBowman2001
**Last updated**: 2022-Dec-11
**Link to download**: [Skylab.zip](https://github.com/levinli303/celestia.mobi/files/10227835/Skylab.zip)

**Comment by DaveBowman2001** [comment]
**Title**: INSAT-1
**Proposed category**: Spacecraft: Communications Satellites
**Author(s)**: DaveBowman2001
**Image**:

**Comment by DaveBowman2001** [comment]
Update to the "**Luna 10**" addon. New CMOD model with visual defects removed

**ID**: [C7E61327-98D1-E0E7-8C7D-7E11D82EE954](https://celestia.mobi/resources/item?item=C7E61327-98D1-E0E7-8C7D-7E11D82EE954)
**Last updated**: 2022-Dec-2
**Link to download**: [Luna 10.zip](https://github.com/levinli303/celestia.mobi/files/10251549/Luna.10.zip)
**Image**:
![Untitled](https://user-images.githubusercontent.com/95486841/208238825-d1e4039d-7ba5-4138-b5a9-2e734c653491.jpg)

**Comment by DaveBowman2001** [comment]
**Title**: BlackSky GLOBAL
**Description (Plain Text)**: The BlackSky constellation is a series of small 55 kg earth observation microsatellites about 0.84 m across that produce 1000 images of the Earth's surface every day in 1-m resolution. As of 2022, a total of 16 out of 18 satellites are currently active in LEO, with the other two being destroyed during a launch failure of an Electron rocket in May 2021. A full constellation of 60 satellites are planned in the near future
**Proposed category**: Spacecraft: Earth Science
**Demo Object name**: BlackSky-17
**Author(s)**: DaveBowman2001, gironde
**Release date**: 2020-Dec-9
**Last updated**: 2022-Oct-27
**Link to download**: [BlackSky GLOBAL.zip](https://github.com/levinli303/celestia.mobi/files/10251556/BlackSky.GLOBAL.zip)
**Image**: 
![Untitled](https://user-images.githubusercontent.com/95486841/208239135-8fb501d9-c187-4297-9a48-c504ce3861b1.jpg)

**Comment by DaveBowman2001** [comment]
**Title**: GOES-13 to 15
**Description (Plain Text)**: GOES-N is the third-generation series of weather satellites under NASA/NOAA's Geostationary Operational Environmental Satellites program (1975-Present). Three satellites of this series (designated as 13, 14, and 15) are launched from 2006-2010. They are planned to be replaced by the fourth-generation GOES-R
**Proposed category**: Spacecraft: Earth Science
**Demo Object name**: GOES-15
**Author(s)**: DaveBowman2001, gironde
**Link to download**: [GOES-N.zip](https://github.com/levinli303/celestia.mobi/files/10251572/GOES-N.zip)
**Image**: 
![Untitled](https://user-images.githubusercontent.com/95486841/208239562-bf385fb0-2955-4b14-ae56-c867f8f0449d.jpg)

**Comment by SpaceExplorer2008** [comment]
Update to the "DART" addon. This is to become fully compatible with the update patch to "65803 Didymos" above

**ID:** 35DD15C3-F872-8561-4302-45B7FD337221
**Author(s):** Limax7, John van Vliet, N3cronium
**Last Updated**2022-Nov-22
**Link to download:**DART.zip
**Image:**
![20221122_153856.jpg](https://user-images.githubusercontent.com/99847641/208240061-53850145-0219-4d5c-9e25-b262666a9f9f.jpg)

**Comment by DaveBowman2001** [comment]
**Title:** C/NOFS
**Description (Plain Text)**: The Communications/Navigation Outage Forecasting System (C/NOFS) satellite was an USAF mission to investigate and forecast scintillations in the Earth's ionosphere. It was launched by an Orbital Sciences Corporation Pegasus-XL launch vehicle at 2008-Apr-16 and decayed on 2015-Nov-28
**Proposed category:** Spacecraft: Technology Demonstrators
**Demo Object Name:** C-NOFS
**Author(s):** gironde
**Release date:** 2018-Jun-4
**Last updated**: 2022-Dec-17
**Link to download:** [C-NOFS.zip](https://github.com/levinli303/celestia.mobi/files/10251601/C-NOFS.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208240195-85a18dad-bcc4-4eff-919d-2a3e7f4f95f0.jpg)

**Comment by SpaceExplorer2008** [comment]
@DaveBowman2001 Will you update the LCROSS addon, due to the upload of the "Centaur III(5)" addon?

**Comment by DaveBowman2001** [comment]
**Title:** Thaicom-4
**Description (Plain Text)**: Thaicom 4, also known as iPStar-1 and MEASAT 5, is an Asian communications satellite built by Space Systems/Loral. Launched in August 2005, it is one of the heaviest communications satellites ever launched into GEO, and it is still in active operations as of 2022
**Proposed category:** Spacecraft: Communications Satellites
**Demo Object Name:** Thaicom-4
**Author(s):** gironde
**Release date:** 2018-Jun-29
**Last Updated:** 2022-Dec-14
**Link to download:** [Thaicom 4.zip](https://github.com/levinli303/celestia.mobi/files/10251612/Thaicom.4.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208240650-8f4b130d-4b15-4d9f-b2f0-f5c1075eba38.jpg)

**Comment by DaveBowman2001** [comment]
Update to the "**LCROSS**" addon. Removed the files for its Centaur booster as it's already provided by the Centaur-III(5) addon. Also a Description update while retaining its old gallery

**ID**: [A79B502E-E959-86EE-4155-1D881B841006](https://celestia.mobi/resources/item?item=A79B502E-E959-86EE-4155-1D881B841006)
**Description (Plain Text)**: The Lunar Crater Observation and Sensing Satellite (LCROSS) is a NASA space mission launched with LRO on June 18, 2009. It was intentionally crashed on the lunar south pole along with its Centaur booster over Cabeus Crater on October 6, 2009 where it confirmed the presence of water ice in the region, crucial to the foundations of future lunar bases like NASA's Artemis Base Camp and the joint-Russian/Chinese ILRS by the 2030s

NOTE: LCROSS's Centaur booster requires the Centaur-III(5) addon installed to be viewed on Celestia

**Description**: The Lunar Crater Observation and Sensing Satellite (LCROSS) is a NASA space mission launched with [LRO](https://celestia.mobi/resources/item?item=875D166F-3E74-3C2A-0D69-35BAE4D59DE7) on June 18, 2009. It was intentionally crashed on the lunar south pole along with its Centaur booster over Cabeus Crater on October 6, 2009 where it confirmed the presence of water ice in the region, crucial to the foundations of future lunar bases like NASA's Artemis Base Camp and the joint-Russian/Chinese ILRS by the 2030s

NOTE: LCROSS's Centaur booster requires the [Centaur-III(5)](https://celestia.mobi/resources/item?item=B4F87DF9-5CDA-4CB5-9E09-848C6E8F1000) addon installed to be viewed on Celestia

**Link to download**: [LCROSS.zip](https://github.com/levinli303/celestia.mobi/files/10251642/LCROSS.zip)

**Comment by SpaceExplorer2008** [comment]
**Title:** Fictional Rogue Planets v.1
**Description (Plain Text):** This addon adds 30 fictional rogue planets scattered across the Milky Way. Each rogue planet is at random positions in the galaxy, with varying distances, from the nearby of the Solar System to thousands of light years away. Each has a different radius, oblatness, and period of rotation. Some contain auroras, some don't.

This addon will be updated from time to time to include many more rogue planets.

**Description:** This addon adds 30 fictional rogue planets scattered across the Milky Way. Each rogue planet is at random positions in the galaxy, with varying distances, from the nearby of the Solar System to thousands of light years away. Each has a different radius, oblatness, and period of rotation. Some contain auroras, some don't.

This addon will be updated from time to time to include many more rogue planets.

NOTES: 

- None have their own name. They must be found by "Rogue Planet" + number. Example: Rogue Planet 1

- As the barycenter method is used, when going to the rogue planet, remember to get closer it

- If the ambient light on your Celestia is set to zero, rogue planets will be shown dark with no lighting. So remember to increase the ambient light in Celestia's settings.

**Proposed Category:** Fictional: Planets & Systems
**Demo Object Name:** Rogue Planet 1
**Author(s):** SpaceExplorer
**Release date:** 2022-12-16
**Link to download:** https://drive.google.com/file/d/1Pq41udU4DXDAxFsR_9f_p1xLlHEu0wW9/view?usp=drivesdk
**Image:** ![rogueplanets.jpg](https://user-images.githubusercontent.com/99847641/208241514-d1437ccc-4b55-41e6-986a-e774310d471b.jpg)

**Comment by SpaceExplorer2008** [comment]
Update [2001 SN263](https://celestia.mobi/resources/item?item=B9D623F9-2043-5502-3601-6356EF013B10)
**ID:** B9D623F9-2043-5502-3601-6356EF013B10

**Title:** (153591) 2001 SN263
**Description (Plain Text):** (153591) 2001 SN263 is a near-Earth C-type asteroid. It was discovered on September 20, 2001 by the LINEAR project. 2001 SN263 has two moons around it, which were discovered in 2008. It can also be recognized as a trinary asteroid system. It is the target of the ASTER mission of the Brazilian Space Agency, with a proposed launch for 2025.

**Comment by SpaceExplorer2008** [comment]
Fixed categories of the following addons:

Update [2018 LA](https://celestia.mobi/resources/item?item=78A2232C-7FD5-4711-AD97-F765007326CE)
**ID:** 78A2232C-7FD5-4711-AD97-F765007326CE

**Proposed Category:** Asteroids & NEOs: Earth Impactors

Update Kepler-1049[](https://celestia.mobi/resources/item?item=617F66CC-1BD3-4E3A-A55C-C823B9185032)
**ID:** 617F66CC-1BD3-4E3A-A55C-C823B9185032

**Proposed Category:** Exoplanets: Confirmed (K)

```
78A2232C-7FD5-4711-AD97-F765007326CE
617F66CC-1BD3-4E3A-A55C-C823B9185032

```

**Comment by SpaceExplorer2008** [comment]
**Title:** Comets 2021
**Description (Plain Text):** This addon adds 52 comets discovered in the year 2021. 

NOTE: Does not include Comet [C/2021 A1 (Leonard)](https://celestia.mobi/resources/item?item=A5006779-694A-1139-D643-08BDCD0B875E), which is available in a separate addon.

**Comment by DaveBowman2001** [comment]
Image/Description Update to the "**TERRIERS**" addon as it had the same info as the POES addon

**ID**: [C97A1ADA-88AD-4FAF-A3A0-FC20BB029C3E](https://celestia.mobi/resources/item?item=C97A1ADA-88AD-4FAF-A3A0-FC20BB029C3E)
**Description (Plain Text/Rich)**: TERRIERS, also known as Explorer 76 and STEDI-2, is a student-built satellite intended to study the Earth's ionosphere. Although launched successfully by a Pegasus-XL rocket in 1999-May-18, its batteries were unable to recharge when it cannot track the Sun and therefore lost contact just two days later, resulting in a mission failure. As of 2022, it is still in orbit as a derelict object
**Image**: 
![Untitled](https://user-images.githubusercontent.com/95486841/207595935-cf5b15fd-e27e-4323-9a82-b662cedc0400.jpg)

**Comment by DaveBowman2001** [comment]
**Title:** HD 191939
**Description (Plain Text)**: HD 191939, also known as TOI-1339, is a Sun-like star about 175.12 light-years away in the constellation Draco. Between 2020 and 2021, a total of five planets (two jovians and three neptunians) were discovered by the TESS observatory, with an additional superterran's existence currently awaiting confirmation
**Proposed category:** Exoplanets: H, I and J
**Demo Object Name:** HD 191939
**Author(s):** QuantumJack1
**Release date:** 2022-Sept-30
**Link to download:** [HD 191939.zip](https://celestia.space/forum/download/file.php?id=14296&filename=HD+191939.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208357419-a2c2aea5-5afd-4913-a16f-db86ba62e77a.jpg)

**Comment by DaveBowman2001** [comment]
**Title:** WASP-104
**Description (Plain Text)**: WASP-104, also known as TOI-5142 and Gaia-TROI-214, is a binary star system comprising of a Sun-like star and a red dwarf star about 609.66 light-years away in the constellation Leo. The larger star of the two has a superjovian planet that absorbs 97% of light coming from its star despite its close distance of 4.79 million km, making it one of the darkest known exoplanets ever discovered (after TrES-2 Ab)
**Proposed category:** Exoplanets: W
**Demo Object Name:** WASP-104 A
**Author(s):** 星颜Crazy
**Release date:** 2022-Sept-25
**Link to download:** [WASP-104.zip](https://celestia.space/forum/download/file.php?id=14300&filename=WASP-104.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208357629-1a325bb2-bf76-4a88-85d8-8e877b440e99.jpg)

**Comment by DaveBowman2001** [comment]
**Title:** Qatar-9
**Description (Plain Text)**: Qatar-9, also known as TOI-3846 and Gaia-TROI-117, is a K-type main sequence star about 689.55 light-years away in the constellation Ursa Major. A Jupiter-sized exoplanet completes an orbit once every 1.54 days at a distance of 3.14 million km from its star
**Proposed category:** Exoplanets: Q, R and S
**Demo Object Name:** Qatar-9
**Author(s):** Pan-STARRS
**Release date:** 2022-Sept-25
**Link to download:** [Qatar-9.zip](https://celestia.space/forum/download/file.php?id=14335&filename=Qatar-9.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208357931-fee2753d-d929-4859-b270-053fd37bbf93.jpg)

**Comment by SpaceExplorer2008** [comment]
**Title:** Periodic Comets: 82P to 102P
**Description (Plain Text):** This addon adds the following 12 comets below as part of a periodic comets catalog.

**Description:** This addon adds the following 12 comets below as part of a periodic comets catalog.

List of comets included in this addon:

- 82P/Gehrels
- 83D/Russell (lost comet)
- 84P/Giclas
- 85P/Boethin
- 86P/Wild
- 87P/Bus
- 88P/Howell
- 89P/Russell
- 90P/Gehrels
- 91P/Russell
- 92P/Sanguin
- 93P/Lovas
- 94P/Russell
- 96P/Machholz
- 97P/Metcalf-Brewington
- 98P/Takamizawa
- 99P/Kowal
- 100P/Hartley
- 101P/Chernykh + 1 debris
- 102P/Shoemaker

**Proposed Category:** Comets 
**Demo Object Name:** 88P Howell
**Author(s):** Art Blos
**Release date:** 2022-12-19
**Link to download:**

**Comment by SevenSpheres** [comment]
> Title: HD 191939

This addon is outdated, since a sixth planet (different from the previously proposed candidate) was discovered last month.

**Comment by DaveBowman2001** [comment]
**Title:** QZ Serpentis
**Description (Plain Text)**: QZ Serpentis is a binary star system consisting of a red dwarf and a white dwarf about 1,048 light-years away in the constellation Serpens Caput. The two stars orbit each other once every 2 hours, with a possible third substellar companion only about half the mass of Jupiter accompanying them
**Proposed category:** Exoplanets: Unconfirmed
**Demo Object Name:** QZ Ser
**Author(s):** Gurren Lagann
**Release date:** 2022-Sept-21
**Link to download:** [QZ Serpentis.zip](https://github.com/levinli303/celestia.mobi/files/10278240/QZ.Serpentis.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208909642-cc079bbe-71b1-447e-ac85-478c301ae6a6.jpg)

**Comment by DaveBowman2001** [comment]
**Title:** HD 82943
**Description (Plain Text)**: HD 82943 is a Sun-like star about 90.06 light-years away in the constellation Hydra. It has two gas giant planets larger than Jupiter that are orbiting within their host star's habitable zone.

NOTE: There are no known exomoons detected in this system, therefore the sole moon orbiting HD 82943 c is entirely fictional

**Proposed category:** Exoplanets: H, I and J
**Demo Object Name:** HD 82943
**Author(s):** SolanaBogon, Thomas Guilpain, Cham, jmdollan
**Release date:** 2012-Jan-13
**Link to download:** [HD 82943.zip](https://github.com/levinli303/celestia.mobi/files/10278242/HD.82943.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208921059-57daed5d-1186-4f4e-bc1c-dc99d0188156.jpg)

**Comment by DaveBowman2001** [comment]
**Title:** MXB 1658-298
**Description (Plain Text)**: MXB 1658-298, also known as V2134 Ophiuchi, is a distant X-ray binary star system consisting of a pulsar and a K-type main sequence star about 32,615 light-years away in the constellation Ophiuchus. In 2017, a massive substellar companion about 23 times the mass of Jupiter was detected via eclipse timing variations, completing a single orbit around both stars once every 2.1 years
**Proposed category:** Exoplanets: M and N
**Demo Object Name:** MXB 1658-298
**Author(s):** SevenSpheres, Cham, Vision
**Release date:** 2020-Aug-14 
**Link to download:** [MXB 1658-298.zip](https://github.com/levinli303/celestia.mobi/files/10278246/MXB.1658-298.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208667739-911cce06-116f-4e9b-87eb-dbb4394fef94.jpg)

**Comment by DaveBowman2001** [comment]
**Title:** 11 Ursae Minoris
**Description (Plain Text)**: 11 Ursae Minoris, also known as Pherkad Minor, is a K-type subgiant star about 410.06 light-years away in the constellation Ursa Minor. In 2009, a superjovian planet about 10 times the mass of Jupiter was discovered via radial velocity by the Thuringian State Observatory in Germany
**Proposed category:** Exoplanets: 0 to 9
**Demo Object Name:** 11 UMi
**Author(s):** SpaceStalker
**Release date:** 2022-Aug-23
**Link to download:** [11 Ursae Minoris.zip](https://github.com/levinli303/celestia.mobi/files/10278257/11.Ursae.Minoris.zip)
**Image:**
![Untitled](https://user-images.githubusercontent.com/95486841/208654939-a18221ab-c60e-43f9-a8f2-da4cd4bfbda6.jpg)

**Comment by levinli303** [comment]
I'll lock this issue when it until all add-ons are uploaded.

**Comment by levinli303** [comment]
I will be making a special type of file format that you can upload your add-on in so as to reduce the hassle for me to re-fill information every time.

**Comment by levinli303** [comment]
Please upload add-on in the format specified below:

Everything should be packaged in a .zip file. The zip file should be structured like this, those marked * are mandatory

```
title.txt *
description.txt *
authors.txt
release_date.txt *
last_update_date.txt
category.txt
demo_object_name.txt
localized_titles.json
localized_descriptions.json
addon.zip *
cover_image.jpg *
id_requirement.txt

rich_description (folder, optional, if provided, those marked * are mandatory)
- base.txt *
- notes.txt
- cover_image.jpg *
- cover_image.txt
- youtube_ids.txt
- detail_image_x.jpg
- detail_image_x.txt
- additional_leading.html
- additional_trailing.html
```

Content of each files:

**title.txt**: Title of the add-on
**description.txt**: Plain description of the add-on
**authors.txt**: Authors, one author per line. (to remove an add-on, do not provide this file)
**release_date.txt**: Release date in yyyy/MM/dd HH:mm:ss format, GMT time zone
**last_update_date.txt**: Last update date in yyyy/MM/dd HH:mm:ss format, GMT time zone
**category.txt**: Category ID,  for example `https://celestia.mobi/resources/category?category=DEAF9C38-7E4B-7DFB-CA72-B496B1652550` has category ID `DEAF9C38-7E4B-7DFB-CA72-B496B1652550` (to remove an add-on, do not provide this file)
**demo_object_name.txt**: Demo object name of the add-on
**localized_titles.json**: Localized title in JSON format, used for non-English locale, for example `{ "zh_CN": "标题" }`
**localized_descriptions.json**: Localized plain description in JSON format, used for non-English locale, for example `{ "zh_CN": "介绍" }`
**addon.zip**: Addon
**cover_image.jpg**: Cover image
**id_requirement.txt**: ID requirement for the add-on ID to start with or the add-on ID to modify if provided in full

**rich_description**: Rich description folder
**base.txt**: The first part of rich description text
**notes.txt**: Notes, one note per line
**cover_image.jpg**: Cover image
**cover_image.txt**: Caption for cover image
**youtube_ids.txt**: YouTube ID, one ID per line, for example `https://www.youtube.com/watch?v=g2ra7EdttTQ` has ID `g2ra7EdttTQ`
**detail_image_x.jpg**: Other image, x will be replaced with number starting from 0
**detail_image_x.txt** Captions for other image x
**additional_leading.html**: Raw HTML content inserted after cover image
**additional_trailing.html**: Raw HTML content inserted at the end

You can have links in `base.txt` and `notes.txt`, use `<a href="link">link display name</a>`. For add-on links, use `celaddon://item?item=ADDON_ID`, for articles use `celguide://guide?guide=GUIDE_ID` as link. Line breaks are ignored in `base.txt`, replace line breaks with `<br>`, replace `>` with `&gt;`, and `<` with `&lt;`

**Comment by levinli303** [comment]
unlocking conversation

**Comment by Spaceforcetrump** [comment]
You're doing a really great job here, that's what I wanted to tell you.  I wish you a Merry Christmas and a Merry Christmas.  Greetings from Sydney.

**Comment by DaveBowman2001** [comment]
## C/NOFS
**Link to download:** [C-NOFS.zip](https://github.com/levinli303/celestia.mobi/files/10300408/C-NOFS.zip)
## Thaicom-4
**Link to download:** [Thaicom-4.zip](https://github.com/levinli303/celestia.mobi/files/10300420/Thaicom-4.zip)
## Kepler-857
**Link to download:** [Kepler-857.zip](https://github.com/levinli303/celestia.mobi/files/10300421/Kepler-857.zip)

**Comment by SpaceExplorer2008** [comment]
@levinli303 This new method slows things down a bit for me, much slower than the previous method. Can add-ons be submitted using the previous method?

**Comment by DaveBowman2001** [comment]
Image/Description Update to the **TERRIERS** addon as it had the same information as the POES addon

**Link to download**: [TERRIERS.zip](https://github.com/levinli303/celestia.mobi/files/10301119/TERRIERS.zip) (no addon.zip included)

**Comment by levinli303** [comment]
provide zip with a structure, not separate files

> @levinli303 This new method slows things down a bit for me, much slower than the previous method. Can add-ons be submitted using the previous method? Honestly, I find the previous method easier.

please get someone to do it for you, this is a tradeoff because of my limit of time

**Comment by SpaceExplorer2008** [comment]
But if submissions are sent at a lower frequency, is it possible? Structuring this new way also consumes my time, much more than the previous method.

**Comment by levinli303** [comment]
> But if submissions are sent at a lower frequency, is it possible? Structuring this new way also consumes my time, much more than the previous method.

No, I'm not accepting submission in old formats.

**Comment by DaveBowman2001** [comment]
> provide zip with a structure, not separate files

Is this for the Voskhod and TERRIERS submissions or all of the new submissions I've made so far? I'm a little bit confused on how to submit updates for those without addon.zip included

**Comment by levinli303** [comment]
> Is this for the Voskhod and TERRIERS submissions or all of the new submissions I've made so far? I'm a little bit confused on how to submit updates for those without addon.zip included

only provide the files changed. if you only change title, then only provide title.txt in .zip file. (the special case is for rich description, you have to provide the entire folder even if only one file inside is changed.)

**Comment by DaveBowman2001** [comment]
Also, does the additional_leading.html and additional_trailing.html provide the Tables from the previous format?

**Comment by levinli303** [comment]
> Also, does the additional_leading.html and additional_trailing.html provide the Tables from the previous format?

```
<table>
table content
</table>
<i class="text-secondary-size text-secondary-color">caption</I>
```

**Comment by levinli303** [comment]
> Resubmitting some previous submissions to match the new template provided:
> 
> ## 11 Ursae Minoris
> **Link to download:** [11 Ursae Minoris.zip](https://github.com/levinli303/celestia.mobi/files/10301047/11.Ursae.Minoris.zip)
> 
> ## C/NOFS
> **Link to download:** [C-NOFS.zip](https://github.com/levinli303/celestia.mobi/files/10300408/C-NOFS.zip)
> 
> ## Kepler-857
> **Link to download:** [Kepler-857.zip](https://github.com/levinli303/celestia.mobi/files/10300421/Kepler-857.zip)
> 
> ## Kepler-1351
> **Link to download:** [Kepler-1351.zip](https://github.com/levinli303/celestia.mobi/files/10300427/Kepler-1351.zip)
> 
> ## MXB 1658-298
> **Link to download:** [MXB 1658-298.zip](https://github.com/levinli303/celestia.mobi/files/10300455/MXB.1658-298.zip)
> 
> ## Qatar-9
> **Link to download:** [Qatar-9.zip](https://github.com/levinli303/celestia.mobi/files/10300444/Qatar-9.zip)
> 
> ## QZ Serpentis
> **Link to download:** [QZ Serpentis.zip](https://github.com/levinli303/celestia.mobi/files/10300451/QZ.Serpentis.zip)
> 
> ## Thaicom-4
> **Link to download:** [Thaicom-4.zip](https://github.com/levinli303/celestia.mobi/files/10300420/Thaicom-4.zip)
> 
> ## WASP-104
> **Link to download:** [WASP-104.zip](https://github.com/levinli303/celestia.mobi/files/10300433/WASP-104.zip)

Need to provide category ID not category name in category.txt

**Comment by DaveBowman2001** [comment]
All `category.txt` files have now been changed to IDs https://github.com/levinli303/celestia.mobi/issues/47#issuecomment-1364714118

**Comment by DaveBowman2001** [comment]
## Project Apollo
**Link to download**: [Project Apollo.zip](https://github.com/levinli303/celestia.mobi/files/10301359/Project.Apollo.zip)

**Comment by DaveBowman2001** [comment]
# Apollo-Soyuz Test Project
**Link to download:** [Apollo-Soyuz Test Project.zip](https://github.com/levinli303/celestia.mobi/files/10301726/Apollo-Soyuz.Test.Project.zip)

**Comment by DaveBowman2001** [comment]
Update to the "**HD 24064**" addon. New planet texture created

**Link to download:** [HD 24064.zip](https://github.com/levinli303/celestia.mobi/files/10301146/HD.24064.zip)
##
Update to the "**Luna 10**" addon. New CMOD model with visual defects removed

**Link to download**: [Luna 10.zip](https://github.com/levinli303/celestia.mobi/files/10301158/Luna.10.zip)

**Comment by levinli303** [comment]
I'm also going to suggest putting multiple zips in a single zip when you are uploading add-ons

**Comment by levinli303** [comment]
> Update to the "**HD 24064**" addon. New planet texture created
> 
> **Link to download:** [HD 24064.zip](https://github.com/levinli303/celestia.mobi/files/10301146/HD.24064.zip)
> 
> Update to the "**Luna 10**" addon. New CMOD model with visual defects removed
> 
> **Link to download**: [Luna 10.zip](https://github.com/levinli303/celestia.mobi/files/10301158/Luna.10.zip)
> 
> Update to the "**Skylab**" addon. Removed all Apollo-related files in the addon as it is already provided by Project Apollo (Part 4). Also a new Description, and requesting to remove its Table
> 
> **Link to download**: [Skylab.zip](https://github.com/levinli303/celestia.mobi/files/10301789/Skylab.zip)

they should contain id_requirement.txt not id.txt

**Comment by levinli303** [comment]
> ## Apollo-Soyuz Test Project
> **Link to download:** [Apollo-Soyuz Test Project.zip](https://github.com/levinli303/celestia.mobi/files/10301726/Apollo-Soyuz.Test.Project.zip)
> 
> ## GOES-13 to 15
> **Link to download:** [GOES-13 to 15.zip](https://github.com/levinli303/celestia.mobi/files/10301872/GOES-13.to.15.zip)
> 
> ## INSAT-1
> **Link to download:** [INSAT-1.zip](https://github.com/levinli303/celestia.mobi/files/10301829/INSAT-1.zip)

this looks wrong:

https://celestia.mobi/resources/item?item=C3BCD43D-B262-4593-95F6-00BAA2B81A8E

entries in notes.txt should just be the text (HTML) you want, do not add `-` to indicate it is a list item.

**Comment by SpaceExplorer2008** [comment]
Link to download: https://drive.google.com/file/d/1WWCsOc3AWYeuxD8xW46emMk2lfMgPOgf/view?usp=drivesdk

**Comment by SpaceExplorer2008** [comment]
Updated names and description of the following addons:

**2001 SN263**
Link to download: https://drive.google.com/file/d/1WXVcRP5Ooba48qxXaXnA1j1fnlRNZkKu/view?usp=drivesdk

**2004 BL86**
Link to download: https://drive.google.com/file/d/1WdF1Kqp665ffAn2j7ypxPyN_knR0br1V/view?usp=drivesdk

**2005 YU55**
Link to download: https://drive.google.com/file/d/1WgbIwk8TGeWiKXsw2lCYYuPbnQBeu7h2/view?usp=drivesdk

**Comment by SpaceExplorer2008** [comment]
At another time I will modify the other submissions, when I have more time.

**Comment by levinli303** [comment]
@SpaceExplorer2008  the format is wrong. these files have to be directly inside the archive.

```
DART.zip
- addon.zip
- etc...
```

What you uploaded is 


```
DART.zip
- DART
- - addon.zip
- - etc...
```

**Comment by SpaceExplorer2008** [comment]
Fixed, in the same post

**Comment by levinli303** [comment]
@SpaceExplorer2008  I'm still seeing the top-level folder which should be removed. and it is id_requirement.txt not id.txt.

 <img width="543" alt="Screenshot 2022-12-27 at 09 57 03" src="https://user-images.githubusercontent.com/17924287/209599042-ba8f4c0e-17e4-4cac-8007-ed76eac5eaa9.png">

**Comment by SpaceExplorer2008** [comment]
Fixed only the DART. I'll do the rest tomorrow, it's already late where I live.

**Comment by levinli303** [comment]
> Fixed only the DART. I'll do the rest tomorrow, it's already late where I live.

<img width="827" alt="Screenshot 2022-12-27 at 10 00 56" src="https://user-images.githubusercontent.com/17924287/209599366-3dfe6559-0a17-4e07-bf60-39bd9b8d6222.png">

not fixed in DART either just FYI.

**Comment by SpaceExplorer2008** [comment]
DART corrected again. I hope that's correct.

Why can't you just do it yourself? Just delete a folder, simple. I, however, need to reload everything to Drive again because of just a folder structure. This is irritating. This method also increases the chances of potential errors.

**Comment by levinli303** [comment]
> DART corrected again. I hope that's correct.
> 
> Why can't you just do it yourself? Just delete a folder, simple. I, however, need to reload everything to Drive again because of just a folder structure. This is irritating. This method also increases the chances of potential errors.

Because I use program to upload add-ons to make up for my lack of time now. Programs only understand fixed paths.

**Comment by DaveBowman2001** [comment]
> this looks wrong...entries in notes.txt should just be the text (HTML) you want, do not add `-` to indicate it is a list item.

Yep you're right..they do look wrong
Will provide fixes at a later time, thanks

**Comment by DaveBowman2001** [comment]
Provided a **Template.zip** on the first post.... @levinli303 if I've missed anything lemme know thanks

**Comment by SpaceExplorer2008** [comment]
@levinli303 If possible, upload the DART update already, because there were problems with the original upload.

**Comment by DaveBowman2001** [comment]
Why not just restructure your DART update from scratch? You could look into the Template I've provided above

**Comment by SpaceExplorer2008** [comment]
But isn't it correct anymore? I followed as explained in the first post.

**Comment by DaveBowman2001** [comment]
No, there shouldn't be a DART folder compiling the required files

**Comment by SpaceExplorer2008** [comment]
Ok, but if, for example, I unzip one of your addons (e.g. INSAT-1), a folder will be formed with the files inside. Just as the DART addon is structured. What I needed to correct was just removing the structure with two DART folders, which should be just one.

**Comment by DaveBowman2001** [comment]
There won't be an outside folder created if you manually drag the contents outside to the extras folder....my advice is that don't use WinRAR's (or any other equivalent software) built-in unzipping function to not encounter that problem

**Comment by levinli303** [comment]
I've edited the program and relaxed some requirements:

1. it can contain a structure of one top folder now (as long as it is not named "rich_description")
2. id.txt is accepted (it is treated the same as id_requirement.txt)

All uploaded.

**Comment by levinli303** [comment]
Adding an alternative way to uploading add-ons:

You can use this (still work in progress) web page to upload add-ons, register an Apple ID if you don't have one.
Login with your Apple ID and then it will show a form. 

<img width="533" alt="Screenshot 2022-12-28 at 15 00 22" src="https://user-images.githubusercontent.com/17924287/209772086-315236d8-5ac1-4184-81ec-05547c36a622.png">

Fill in the information needed and then click Submit, if submission is successful you will get an ID, post the ID here.

https://celestia.mobi/resources/guide?guide=50159230-8582-7CBA-3674-E63A63F6693B

**Comment by SpaceExplorer2008** [comment]
@levinli303 I don't use any Apple devices or services, but I tried to create an Apple ID and I couldn't, the code sent to me didn't work, even after several attempts. Is there any other alternative to register?

**Comment by levinli303** [comment]
@SpaceExplorer2008  You don't need to have apple device or use apple services to have an Apple ID, check why you failed to register an Apple ID online. https://appleid.apple.com is where you register.

**Comment by Spaceforcetrump** [comment]
Hello Levilin I have a question there is a new function in Google Earth and you can calculate the radius of the earth and I came up with 34290 kilometers and not 12742 kilometers.

**Comment by SpaceExplorer2008** [comment]
This is exactly where I tried to create the ID, however even when entering the correct code when verifying the phone number it doesn't proceed to the next step. I will try on another device.

**Comment by SpaceExplorer2008** [comment]
> Hello Levilin I have a question there is a new function in Google Earth and you can calculate the radius of the earth and I came up with 34290 kilometers and not 12742 kilometers.

Please, this is not a subject for this issue.

**Comment by SpaceExplorer2008** [comment]
**Comets 2021**

Link to download: https://drive.google.com/file/d/1_Pp_Ltux5EfCet46Qw_qpM5L-SJnEzCs/view?usp=drivesdk

**Comment by Spaceforcetrump** [comment]
> > Hello Levilin I have a question there is a new function in Google Earth and you can calculate the radius of the earth and I came up with 34290 kilometers and not 12742 kilometers.
> 
> Please, this is not a subject for this issue.

Ok

**Comment by Spaceforcetrump** [comment]
> > Hallo Levilin ich habe eine Frage, es gibt eine neue Funktion in Google Earth und berechnen Sie den radius der Erde, und ich kam mit 34290 Kilometer und nicht 12742 Kilometer.
> 
> Bitte, dies ist kein Thema für dieses Problem.

How to private message Levilin?  Greetings from Australia

**Comment by levinli303** [comment]
> How to private message Levilin? Greetings from Australia

If you have issue with Celestia, please try asking on Celestia forum or Celestia discord. Besides, you seem to have issue with Google Earth, which does not seem to be related to Celestia in the first place.

**Comment by Spaceforcetrump** [comment]
> > Wie man private Nachricht Levilin? Grüße aus Australien
> 
> Wenn Sie haben Problem mit Celestia, bitte versuchen Sie, auf Celestia forum oder Celestia discord. Neben, Sie scheinen zu haben, die Problem mit Google Earth, die nicht verbunden zu sein scheint, um Celestia in den ersten Platz.

OK

**Comment by Spaceforcetrump** [comment]
> > Wie man private Nachricht Levilin? Grüße aus Australien
> 
> Wenn Sie haben Problem mit Celestia, bitte versuchen Sie, auf Celestia forum oder Celestia discord. Neben, Sie scheinen zu haben, die Problem mit Google Earth, die nicht verbunden zu sein scheint, um Celestia in den ersten Platz.

I just wanted to say that I measured this with Google Earth that the radius of the earth is not 12742 kilometers but 34290 kilometers.  Just wanted to inform you.  Have a nice day from beautiful Sydney

**Comment by DaveBowman2001** [comment]
> ...if submission is successful you will get an ID, post the ID here.

Testing the new submission format if I understand it correctly:

**HD 82943** = 8ACD2743-214B-4F55-9902-1BC2605F094D
**Kepler-40** = B651D5A0-98AE-4605-B13A-43E9E841454F

**Comment by levinli303** [comment]
> https://drive.google.com/file/d/1_Pp_Ltux5EfCet46Qw_qpM5L-SJnEzCs/view?usp=drivesdk

category.txt should contain category ID, not category name.

**Comment by levinli303** [comment]
> > ...if submission is successful you will get an ID, post the ID here.
> 
> Testing the new submission format if I understand it correctly:
> 
> **HD 82943** = 8ACD2743-214B-4F55-9902-1BC2605F094D **Kepler-40** = B651D5A0-98AE-4605-B13A-43E9E841454F **Kepler-421** = 3D6044CD-C0BD-4697-82C9-D406F9EED753

https://celestia.mobi/resources/item?item=52907531-7B13-4525-B243-ABC4F14251FB

This is wrong. Description does not support HTML. so no need for <br>.

**Comment by SpaceExplorer2008** [comment]
Fixed in the same post. I couldn't create an Apple ID even though I did all the steps correctly. The code sent by phone number did not work, even though I tested it on my cell phone and computer. Is it possible to send the form link itself?

**Comment by DaveBowman2001** [comment]
> This is wrong. Description does not support HTML. so no need for .

Ah, I see. One more thing: I tried submitting updates to existing addons, but when I submitted them, the form generated a new random ID...is it also normal for those cases?

**Comment by levinli303** [comment]
> Is it possible for someone to send the link to the form itself?

Nope. Non authenticated users can only have READ permission.

**Comment by levinli303** [comment]
> > This is wrong. Description does not support HTML. so no need for .
> 
> Ah, I see. One more thing: I tried submitting updates to existing addons, but when I submitted them, the form generated a new random ID...is it also normal for those cases?

The ID returned has nothing to do with add-on ID.

**Comment by DaveBowman2001** [comment]
Ooohhh ok, it's getting clearer now...so the generated IDs are just temporary, totally different from what it will be posted on mobi itself

**Comment by DaveBowman2001** [comment]
**Project Apollo** (Authors/Description update) = AA17E3E8-04BD-44AB-8F3F-0E4ADDDB6A73
**Voskhod 1 and 2** (Authors update) = 0464E68B-84B7-41E4-946A-4907BD96C18F

**Comment by levinli303** [comment]
Category option is now a drop down menu.

<img width="880" alt="Screenshot 2022-12-30 at 14 02 09" src="https://user-images.githubusercontent.com/17924287/210039592-66af9d96-0f63-4f10-a526-fa576e5b6e35.png">

**Comment by DaveBowman2001** [comment]
Will be closing this issue for now...Happy New Year everyone!

**Comment by Spaceforcetrump** [comment]
How can you donate money here?  Greetings from Sydney
